exports.samples = {
  '1st Violins': [
  	{note: 'A#', octave: 3, file: 'Samples/1st Violins/1st-violins-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/1st Violins/1st-violins-sus-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/1st Violins/1st-violins-sus-a%235.wav'},
  	{note: 'A#', octave: 6, file: 'Samples/1st Violins/1st-violins-sus-a%236.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/1st Violins/1st-violins-sus-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/1st Violins/1st-violins-sus-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/1st Violins/1st-violins-sus-c%236.wav'},
  	{note: 'E', octave: 4, file: 'Samples/1st Violins/1st-violins-sus-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/1st Violins/1st-violins-sus-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/1st Violins/1st-violins-sus-e6.wav'},
  	{note: 'G', octave: 3, file: 'Samples/1st Violins/1st-violins-sus-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/1st Violins/1st-violins-sus-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/1st Violins/1st-violins-sus-g5.wav'},
  	{note: 'G', octave: 6, file: 'Samples/1st Violins/1st-violins-sus-g6.wav'}
  ],
  '2nd Violins': [
  	{note: 'A#', octave: 3, file: 'Samples/2nd Violins/2nd-violins-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/2nd Violins/2nd-violins-sus-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/2nd Violins/2nd-violins-sus-a%235.wav'},
  	{note: 'A#', octave: 6, file: 'Samples/2nd Violins/2nd-violins-sus-a%236.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/2nd Violins/2nd-violins-sus-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/2nd Violins/2nd-violins-sus-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/2nd Violins/2nd-violins-sus-c%236.wav'},
  	{note: 'E', octave: 4, file: 'Samples/2nd Violins/2nd-violins-sus-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/2nd Violins/2nd-violins-sus-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/2nd Violins/2nd-violins-sus-e6.wav'},
  	{note: 'G', octave: 3, file: 'Samples/2nd Violins/2nd-violins-sus-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/2nd Violins/2nd-violins-sus-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/2nd Violins/2nd-violins-sus-g5.wav'},
  	{note: 'G', octave: 6, file: 'Samples/2nd Violins/2nd-violins-sus-g6.wav'}
  ],
  'Alto Flute': [
    {note: 'A#', octave: 3, file: 'Samples/Alto Flute/alto_flute-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Alto Flute/alto_flute-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Alto Flute/alto_flute-a%235.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Alto Flute/alto_flute-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Alto Flute/alto_flute-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/Alto Flute/alto_flute-c%236.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Alto Flute/alto_flute-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Alto Flute/alto_flute-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/Alto Flute/alto_flute-e6.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Alto Flute/alto_flute-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Alto Flute/alto_flute-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Alto Flute/alto_flute-g5.wav'},
  	{note: 'G', octave: 6, file: 'Samples/Alto Flute/alto_flute-g6.wav'}
  ],
  'Bass Clarinet': [
    {note: 'B', octave: 2, file: 'Samples/Bass Clarinet/bass_clarinet-b2.wav'},
  	{note: 'B', octave: 3, file: 'Samples/Bass Clarinet/bass_clarinet-b3.wav'},
  	{note: 'B', octave: 4, file: 'Samples/Bass Clarinet/bass_clarinet-b4.wav'},
  	{note: 'D', octave: 2, file: 'Samples/Bass Clarinet/bass_clarinet-d2.wav'},
  	{note: 'D', octave: 3, file: 'Samples/Bass Clarinet/bass_clarinet-d3.wav'},
  	{note: 'D', octave: 4, file: 'Samples/Bass Clarinet/bass_clarinet-d4.wav'},
  	{note: 'D', octave: 5, file: 'Samples/Bass Clarinet/bass_clarinet-d5.wav'},
  	{note: 'F', octave: 2, file: 'Samples/Bass Clarinet/bass_clarinet-f2.wav'},
  	{note: 'F', octave: 3, file: 'Samples/Bass Clarinet/bass_clarinet-f3.wav'},
  	{note: 'F', octave: 4, file: 'Samples/Bass Clarinet/bass_clarinet-f4.wav'},
  	{note: 'G#', octave: 2, file: 'Samples/Bass Clarinet/bass_clarinet-g%232.wav'},
  	{note: 'G#', octave: 3, file: 'Samples/Bass Clarinet/bass_clarinet-g%233.wav'},
  	{note: 'G#', octave: 4, file: 'Samples/Bass Clarinet/bass_clarinet-g%234.wav'}
  ],
  'Bass Trombone': [
    {note: 'A#', octave: 1, file: 'Samples/Bass Trombone/bass_trombone-a%231.wav'},
  	{note: 'A#', octave: 2, file: 'Samples/Bass Trombone/bass_trombone-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Bass Trombone/bass_trombone-a%233.wav'},
  	{note: 'C#', octave: 2, file: 'Samples/Bass Trombone/bass_trombone-c%232.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Bass Trombone/bass_trombone-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Bass Trombone/bass_trombone-c%234.wav'},
  	{note: 'E', octave: 1, file: 'Samples/Bass Trombone/bass_trombone-e1.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Bass Trombone/bass_trombone-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Bass Trombone/bass_trombone-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Bass Trombone/bass_trombone-e4.wav'},
  	{note: 'G', octave: 1, file: 'Samples/Bass Trombone/bass_trombone-g1.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Bass Trombone/bass_trombone-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Bass Trombone/bass_trombone-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Bass Trombone/bass_trombone-g4.wav'}
  ],
  'Basses': [
  	{note: 'A', octave: 1, file: 'Samples/Basses/basses-sus-a1.wav'},
  	{note: 'A', octave: 2, file: 'Samples/Basses/basses-sus-a2.wav'},
  	{note: 'A', octave: 3, file: 'Samples/Basses/basses-sus-a3.wav'},
  	{note: 'C', octave: 1, file: 'Samples/Basses/basses-sus-c1.wav'},
  	{note: 'C', octave: 2, file: 'Samples/Basses/basses-sus-c2.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Basses/basses-sus-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Basses/basses-sus-c4.wav'},
  	{note: 'D#', octave: 1, file: 'Samples/Basses/basses-sus-d%231.wav'},
  	{note: 'D#', octave: 2, file: 'Samples/Basses/basses-sus-d%232.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Basses/basses-sus-d%233.wav'},
  	{note: 'F#', octave: 1, file: 'Samples/Basses/basses-sus-f%231.wav'},
  	{note: 'F#', octave: 2, file: 'Samples/Basses/basses-sus-f%232.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Basses/basses-sus-f%233.wav'}
  ],
  'Bassoon': [
    {note: 'A#', octave: 1, file: 'Samples/Bassoon/bassoon-a%231.wav'},
  	{note: 'A#', octave: 2, file: 'Samples/Bassoon/bassoon-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Bassoon/bassoon-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Bassoon/bassoon-a%234.wav'},
  	{note: 'C#', octave: 2, file: 'Samples/Bassoon/bassoon-c%232.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Bassoon/bassoon-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Bassoon/bassoon-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Bassoon/bassoon-c%235.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Bassoon/bassoon-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Bassoon/bassoon-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Bassoon/bassoon-e4.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Bassoon/bassoon-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Bassoon/bassoon-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Bassoon/bassoon-g4.wav'}
  ],
  'Bassoons': [
    {note: 'A#', octave: 1, file: 'Samples/Bassoons/bassoons-sus-a%231.wav'},
  	{note: 'A#', octave: 2, file: 'Samples/Bassoons/bassoons-sus-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Bassoons/bassoons-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Bassoons/bassoons-sus-a%234.wav'},
  	{note: 'C#', octave: 2, file: 'Samples/Bassoons/bassoons-sus-c%232.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Bassoons/bassoons-sus-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Bassoons/bassoons-sus-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Bassoons/bassoons-sus-c%235.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Bassoons/bassoons-sus-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Bassoons/bassoons-sus-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Bassoons/bassoons-sus-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Bassoons/bassoons-sus-e5.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Bassoons/bassoons-sus-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Bassoons/bassoons-sus-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Bassoons/bassoons-sus-g4.wav'}
  ],
  'Celli': [
  	{note: 'A', octave: 2, file: 'Samples/Celli/celli-sus-a2.wav'},
  	{note: 'A', octave: 3, file: 'Samples/Celli/celli-sus-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Celli/celli-sus-a4.wav'},
  	{note: 'C', octave: 2, file: 'Samples/Celli/celli-sus-c2.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Celli/celli-sus-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Celli/celli-sus-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Celli/celli-sus-c5.wav'},
  	{note: 'D#', octave: 2, file: 'Samples/Celli/celli-sus-d%232.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Celli/celli-sus-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Celli/celli-sus-d%234.wav'},
  	{note: 'F#', octave: 2, file: 'Samples/Celli/celli-sus-f%232.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Celli/celli-sus-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Celli/celli-sus-f%234.wav'}
  ],
  'Cello': [
    {note: 'A', octave: 2, file: 'Samples/Cello/cello-a2.wav'},
  	{note: 'A', octave: 3, file: 'Samples/Cello/cello-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Cello/cello-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Cello/cello-a5.wav'},
  	{note: 'C', octave: 2, file: 'Samples/Cello/cello-c2.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Cello/cello-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Cello/cello-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Cello/cello-c5.wav'},
  	{note: 'D#', octave: 2, file: 'Samples/Cello/cello-d%232.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Cello/cello-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Cello/cello-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Cello/cello-d%235.wav'},
  	{note: 'F#', octave: 2, file: 'Samples/Cello/cello-f%232.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Cello/cello-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Cello/cello-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Cello/cello-f%235.wav'}
  ],
  'Female Chorus': [
    {note: 'A#', octave: 4, file: 'Samples/Chorus/chorus-female-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Chorus/chorus-female-a%235.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Chorus/chorus-female-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Chorus/chorus-female-a5.wav'},
  	{note: 'B', octave: 4, file: 'Samples/Chorus/chorus-female-b4.wav'},
  	{note: 'B', octave: 5, file: 'Samples/Chorus/chorus-female-b5.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Chorus/chorus-female-c%235.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Chorus/chorus-female-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Chorus/chorus-female-c6.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Chorus/chorus-female-d%235.wav'},
  	{note: 'D', octave: 5, file: 'Samples/Chorus/chorus-female-d5.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Chorus/chorus-female-e5.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Chorus/chorus-female-f%235.wav'},
  	{note: 'F', octave: 5, file: 'Samples/Chorus/chorus-female-f5.wav'},
  	{note: 'G#', octave: 4, file: 'Samples/Chorus/chorus-female-g%234.wav'},
  	{note: 'G#', octave: 5, file: 'Samples/Chorus/chorus-female-g%235.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Chorus/chorus-female-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Chorus/chorus-female-g5.wav'}
    ],
  'Male Chorus': [
  	{note: 'A#', octave: 2, file: 'Samples/Chorus/chorus-male-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Chorus/chorus-male-a%233.wav'},
  	{note: 'A', octave: 2, file: 'Samples/Chorus/chorus-male-a2.wav'},
  	{note: 'A', octave: 3, file: 'Samples/Chorus/chorus-male-a3.wav'},
  	{note: 'B', octave: 2, file: 'Samples/Chorus/chorus-male-b2.wav'},
  	{note: 'B', octave: 3, file: 'Samples/Chorus/chorus-male-b3.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Chorus/chorus-male-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Chorus/chorus-male-c%234.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Chorus/chorus-male-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Chorus/chorus-male-c4.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Chorus/chorus-male-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Chorus/chorus-male-d%234.wav'},
  	{note: 'D', octave: 3, file: 'Samples/Chorus/chorus-male-d3.wav'},
  	{note: 'D', octave: 4, file: 'Samples/Chorus/chorus-male-d4.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Chorus/chorus-male-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Chorus/chorus-male-e4.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Chorus/chorus-male-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Chorus/chorus-male-f%234.wav'},
  	{note: 'F', octave: 3, file: 'Samples/Chorus/chorus-male-f3.wav'},
  	{note: 'F', octave: 4, file: 'Samples/Chorus/chorus-male-f4.wav'},
  	{note: 'G#', octave: 2, file: 'Samples/Chorus/chorus-male-g%232.wav'},
  	{note: 'G#', octave: 3, file: 'Samples/Chorus/chorus-male-g%233.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Chorus/chorus-male-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Chorus/chorus-male-g3.wav'}
  ],
  'Clarinet': [
    {note: 'B', octave: 3, file: 'Samples/Clarinet/clarinet-b3.wav'},
  	{note: 'B', octave: 4, file: 'Samples/Clarinet/clarinet-b4.wav'},
  	{note: 'B', octave: 5, file: 'Samples/Clarinet/clarinet-b5.wav'},
  	{note: 'D', octave: 3, file: 'Samples/Clarinet/clarinet-d3.wav'},
  	{note: 'D', octave: 4, file: 'Samples/Clarinet/clarinet-d4.wav'},
  	{note: 'D', octave: 5, file: 'Samples/Clarinet/clarinet-d5.wav'},
  	{note: 'D', octave: 6, file: 'Samples/Clarinet/clarinet-d6.wav'},
  	{note: 'F', octave: 3, file: 'Samples/Clarinet/clarinet-f3.wav'},
  	{note: 'F', octave: 4, file: 'Samples/Clarinet/clarinet-f4.wav'},
  	{note: 'F', octave: 5, file: 'Samples/Clarinet/clarinet-f5.wav'},
  	{note: 'G#', octave: 3, file: 'Samples/Clarinet/clarinet-g%233.wav'},
  	{note: 'G#', octave: 4, file: 'Samples/Clarinet/clarinet-g%234.wav'},
  	{note: 'G#', octave: 5, file: 'Samples/Clarinet/clarinet-g%235.wav'}
  ],
  'Clarinets': [
    {note: 'B', octave: 3, file: 'Samples/Clarinets/clarinets-sus-b3.wav'},
  	{note: 'B', octave: 4, file: 'Samples/Clarinets/clarinets-sus-b4.wav'},
  	{note: 'B', octave: 5, file: 'Samples/Clarinets/clarinets-sus-b5.wav'},
  	{note: 'D', octave: 3, file: 'Samples/Clarinets/clarinets-sus-d3.wav'},
  	{note: 'D', octave: 4, file: 'Samples/Clarinets/clarinets-sus-d4.wav'},
  	{note: 'D', octave: 5, file: 'Samples/Clarinets/clarinets-sus-d5.wav'},
  	{note: 'D', octave: 6, file: 'Samples/Clarinets/clarinets-sus-d6.wav'},
  	{note: 'F', octave: 3, file: 'Samples/Clarinets/clarinets-sus-f3.wav'},
  	{note: 'F', octave: 4, file: 'Samples/Clarinets/clarinets-sus-f4.wav'},
  	{note: 'F', octave: 5, file: 'Samples/Clarinets/clarinets-sus-f5.wav'},
  	{note: 'G#', octave: 3, file: 'Samples/Clarinets/clarinets-sus-g%233.wav'},
  	{note: 'G#', octave: 4, file: 'Samples/Clarinets/clarinets-sus-g%234.wav'},
  	{note: 'G#', octave: 5, file: 'Samples/Clarinets/clarinets-sus-g%235.wav'}
  ],
  'Contrabassoon': [
    {note: 'A#', octave: 0, file: 'Samples/Contrabassoon/contrabassoon-a%230.wav'},
  	{note: 'A#', octave: 1, file: 'Samples/Contrabassoon/contrabassoon-a%231.wav'},
  	{note: 'A#', octave: 2, file: 'Samples/Contrabassoon/contrabassoon-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Contrabassoon/contrabassoon-a%233.wav'},
  	{note: 'C#', octave: 1, file: 'Samples/Contrabassoon/contrabassoon-c%231.wav'},
  	{note: 'C#', octave: 2, file: 'Samples/Contrabassoon/contrabassoon-c%232.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Contrabassoon/contrabassoon-c%233.wav'},
  	{note: 'E', octave: 1, file: 'Samples/Contrabassoon/contrabassoon-e1.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Contrabassoon/contrabassoon-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Contrabassoon/contrabassoon-e3.wav'},
  	{note: 'G', octave: 1, file: 'Samples/Contrabassoon/contrabassoon-g1.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Contrabassoon/contrabassoon-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Contrabassoon/contrabassoon-g3.wav'}
  ],
  'Cor Anglais': [
    {note: 'B', octave: 3, file: 'Samples/Cor Anglais/cor_anglais-b3.wav'},
  	{note: 'B', octave: 4, file: 'Samples/Cor Anglais/cor_anglais-b4.wav'},
  	{note: 'D', octave: 4, file: 'Samples/Cor Anglais/cor_anglais-d4.wav'},
  	{note: 'D', octave: 5, file: 'Samples/Cor Anglais/cor_anglais-d5.wav'},
  	{note: 'F', octave: 3, file: 'Samples/Cor Anglais/cor_anglais-f3.wav'},
  	{note: 'F', octave: 4, file: 'Samples/Cor Anglais/cor_anglais-f4.wav'},
  	{note: 'F', octave: 5, file: 'Samples/Cor Anglais/cor_anglais-f5.wav'},
  	{note: 'G#', octave: 3, file: 'Samples/Cor Anglais/cor_anglais-g%233.wav'},
  	{note: 'G#', octave: 4, file: 'Samples/Cor Anglais/cor_anglais-g%234.wav'}
  ],
  'Flute': [
    {note: 'A', octave: 3, file: 'Samples/Flute/flute-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Flute/flute-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Flute/flute-a5.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Flute/flute-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Flute/flute-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Flute/flute-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Flute/flute-c6.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Flute/flute-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Flute/flute-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Flute/flute-d%235.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Flute/flute-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Flute/flute-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Flute/flute-f%235.wav'}
  ],
  'Flutes': [
  	{note: 'A', octave: 3, file: 'Samples/Flutes/flutes-sus-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Flutes/flutes-sus-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Flutes/flutes-sus-a5.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Flutes/flutes-sus-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Flutes/flutes-sus-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Flutes/flutes-sus-c5.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Flutes/flutes-sus-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Flutes/flutes-sus-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Flutes/flutes-sus-d%235.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Flutes/flutes-sus-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Flutes/flutes-sus-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Flutes/flutes-sus-f%235.wav'}
  ],
  'Grand Piano': [
    {note: 'A', octave: 1, file: 'Samples/Grand Piano/piano-f-a1.wav'},
  	{note: 'A', octave: 2, file: 'Samples/Grand Piano/piano-f-a2.wav'},
  	{note: 'A', octave: 3, file: 'Samples/Grand Piano/piano-f-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Grand Piano/piano-f-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Grand Piano/piano-f-a5.wav'},
  	{note: 'A', octave: 6, file: 'Samples/Grand Piano/piano-f-a6.wav'},
  	{note: 'A', octave: 7, file: 'Samples/Grand Piano/piano-f-a7.wav'},
  	{note: 'C', octave: 1, file: 'Samples/Grand Piano/piano-f-c1.wav'},
  	{note: 'C', octave: 2, file: 'Samples/Grand Piano/piano-f-c2.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Grand Piano/piano-f-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Grand Piano/piano-f-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Grand Piano/piano-f-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Grand Piano/piano-f-c6.wav'},
  	{note: 'C', octave: 7, file: 'Samples/Grand Piano/piano-f-c7.wav'},
  	{note: 'C', octave: 8, file: 'Samples/Grand Piano/piano-f-c8.wav'},
  	{note: 'D#', octave: 1, file: 'Samples/Grand Piano/piano-f-d%231.wav'},
  	{note: 'D#', octave: 2, file: 'Samples/Grand Piano/piano-f-d%232.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Grand Piano/piano-f-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Grand Piano/piano-f-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Grand Piano/piano-f-d%235.wav'},
  	{note: 'D#', octave: 6, file: 'Samples/Grand Piano/piano-f-d%236.wav'},
  	{note: 'D#', octave: 7, file: 'Samples/Grand Piano/piano-f-d%237.wav'},
  	{note: 'F#', octave: 1, file: 'Samples/Grand Piano/piano-f-f%231.wav'},
  	{note: 'F#', octave: 2, file: 'Samples/Grand Piano/piano-f-f%232.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Grand Piano/piano-f-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Grand Piano/piano-f-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Grand Piano/piano-f-f%235.wav'},
  	{note: 'F#', octave: 6, file: 'Samples/Grand Piano/piano-f-f%236.wav'},
  	{note: 'F#', octave: 7, file: 'Samples/Grand Piano/piano-f-f%237.wav'}
  ],
  'Harp': [
    {note: 'A', octave: 2, file: 'Samples/Harp/harp-a2.wav'},
  	{note: 'A', octave: 3, file: 'Samples/Harp/harp-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Harp/harp-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Harp/harp-a5.wav'},
  	{note: 'A', octave: 6, file: 'Samples/Harp/harp-a6.wav'},
  	{note: 'C', octave: 2, file: 'Samples/Harp/harp-c2.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Harp/harp-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Harp/harp-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Harp/harp-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Harp/harp-c6.wav'},
  	{note: 'C', octave: 7, file: 'Samples/Harp/harp-c7.wav'},
  	{note: 'D#', octave: 2, file: 'Samples/Harp/harp-d%232.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Harp/harp-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Harp/harp-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Harp/harp-d%235.wav'},
  	{note: 'D#', octave: 6, file: 'Samples/Harp/harp-d%236.wav'},
  	{note: 'F#', octave: 2, file: 'Samples/Harp/harp-f%232.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Harp/harp-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Harp/harp-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Harp/harp-f%235.wav'},
  	{note: 'F#', octave: 6, file: 'Samples/Harp/harp-f%236.wav'}
  ],
  'Horn': [
    {note: 'A#', octave: 2, file: 'Samples/Horn/horn-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Horn/horn-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Horn/horn-a%234.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Horn/horn-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Horn/horn-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Horn/horn-c%235.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Horn/horn-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Horn/horn-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Horn/horn-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Horn/horn-e5.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Horn/horn-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Horn/horn-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Horn/horn-g4.wav'}
  ],
  'Horns': [
  	{note: 'A#', octave: 2, file: 'Samples/Horns/horns-sus-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Horns/horns-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Horns/horns-sus-a%234.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Horns/horns-sus-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Horns/horns-sus-c%234.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Horns/horns-sus-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Horns/horns-sus-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Horns/horns-sus-e4.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Horns/horns-sus-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Horns/horns-sus-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Horns/horns-sus-g4.wav'}
  ],
  'Oboe': [
    {note: 'A#', octave: 3, file: 'Samples/Oboe/oboe-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Oboe/oboe-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Oboe/oboe-a%235.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Oboe/oboe-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Oboe/oboe-c%235.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Oboe/oboe-c6.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Oboe/oboe-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Oboe/oboe-e5.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Oboe/oboe-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Oboe/oboe-g5.wav'}
  ],
  'Oboes': [
    {note: 'A#', octave: 3, file: 'Samples/Oboes/oboes-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Oboes/oboes-sus-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Oboes/oboes-sus-a%235.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Oboes/oboes-sus-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Oboes/oboes-sus-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/Oboes/oboes-sus-c%236.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Oboes/oboes-sus-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Oboes/oboes-sus-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/Oboes/oboes-sus-e6.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Oboes/oboes-sus-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Oboes/oboes-sus-g5.wav'}
  ],
  'Chimes': [
  	{note: 'A', octave: 3, file: 'Samples/Percussion/chimes-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Percussion/chimes-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Percussion/chimes-a5.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Percussion/chimes-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Percussion/chimes-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Percussion/chimes-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Percussion/chimes-c6.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Percussion/chimes-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Percussion/chimes-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Percussion/chimes-d%235.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Percussion/chimes-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Percussion/chimes-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Percussion/chimes-f%235.wav'}
  ],
  'Glockenspiel': [
  	{note: 'A', octave: 3, file: 'Samples/Percussion/glockenspiel-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Percussion/glockenspiel-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Percussion/glockenspiel-a5.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Percussion/glockenspiel-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Percussion/glockenspiel-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Percussion/glockenspiel-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Percussion/glockenspiel-c6.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Percussion/glockenspiel-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Percussion/glockenspiel-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Percussion/glockenspiel-d%235.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Percussion/glockenspiel-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Percussion/glockenspiel-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Percussion/glockenspiel-f%235.wav'}
  ],
  'Xylophone': [
  	{note: 'A#', octave: 2, file: 'Samples/Percussion/xylophone-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Percussion/xylophone-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Percussion/xylophone-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Percussion/xylophone-a%235.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Percussion/xylophone-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Percussion/xylophone-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Percussion/xylophone-c%235.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Percussion/xylophone-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Percussion/xylophone-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Percussion/xylophone-e5.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Percussion/xylophone-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Percussion/xylophone-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Percussion/xylophone-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Percussion/xylophone-g5.wav'}
  ],
  'Piccolo': [
    {note: 'A', octave: 4, file: 'Samples/Piccolo/piccolo-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Piccolo/piccolo-a5.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Piccolo/piccolo-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Piccolo/piccolo-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Piccolo/piccolo-c6.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Piccolo/piccolo-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Piccolo/piccolo-d%235.wav'},
  	{note: 'D#', octave: 6, file: 'Samples/Piccolo/piccolo-d%236.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Piccolo/piccolo-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Piccolo/piccolo-f%235.wav'},
  	{note: 'F#', octave: 6, file: 'Samples/Piccolo/piccolo-f%236.wav'}
  ],
  'Tenor Trombone': [
    {note: 'A#', octave: 2, file: 'Samples/Tenor Trombone/tenor_trombone-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Tenor Trombone/tenor_trombone-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Tenor Trombone/tenor_trombone-a%234.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Tenor Trombone/tenor_trombone-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Tenor Trombone/tenor_trombone-c%234.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Tenor Trombone/tenor_trombone-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Tenor Trombone/tenor_trombone-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Tenor Trombone/tenor_trombone-e4.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Tenor Trombone/tenor_trombone-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Tenor Trombone/tenor_trombone-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Tenor Trombone/tenor_trombone-g4.wav'}
  ],
  'Trombones': [
  	{note: 'A#', octave: 2, file: 'Samples/Trombones/trombones-sus-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Trombones/trombones-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Trombones/trombones-sus-a%234.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Trombones/trombones-sus-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Trombones/trombones-sus-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Trombones/trombones-sus-c%235.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Trombones/trombones-sus-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Trombones/trombones-sus-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Trombones/trombones-sus-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Trombones/trombones-sus-e5.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Trombones/trombones-sus-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Trombones/trombones-sus-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Trombones/trombones-sus-g4.wav'}
  ],
  'Trumpet': [
    {note: 'A#', octave: 3, file: 'Samples/Trumpet/trumpet-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Trumpet/trumpet-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Trumpet/trumpet-a%235.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Trumpet/trumpet-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Trumpet/trumpet-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/Trumpet/trumpet-c%236.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Trumpet/trumpet-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Trumpet/trumpet-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Trumpet/trumpet-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/Trumpet/trumpet-e6.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Trumpet/trumpet-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Trumpet/trumpet-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Trumpet/trumpet-g5.wav'}
  ],
  'Trumpets': [
  	{note: 'A#', octave: 3, file: 'Samples/Trumpets/trumpets-sus-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Trumpets/trumpets-sus-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Trumpets/trumpets-sus-a%235.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Trumpets/trumpets-sus-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Trumpets/trumpets-sus-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/Trumpets/trumpets-sus-c%236.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Trumpets/trumpets-sus-e3.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Trumpets/trumpets-sus-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Trumpets/trumpets-sus-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/Trumpets/trumpets-sus-e6.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Trumpets/trumpets-sus-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Trumpets/trumpets-sus-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Trumpets/trumpets-sus-g5.wav'}
  ],
  'Tuba': [
  	{note: 'A#', octave: 1, file: 'Samples/Tuba/tuba-sus-a%231.wav'},
  	{note: 'A#', octave: 2, file: 'Samples/Tuba/tuba-sus-a%232.wav'},
  	{note: 'A#', octave: 3, file: 'Samples/Tuba/tuba-sus-a%233.wav'},
  	{note: 'C#', octave: 2, file: 'Samples/Tuba/tuba-sus-c%232.wav'},
  	{note: 'C#', octave: 3, file: 'Samples/Tuba/tuba-sus-c%233.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Tuba/tuba-sus-c%234.wav'},
  	{note: 'E', octave: 1, file: 'Samples/Tuba/tuba-sus-e1.wav'},
  	{note: 'E', octave: 2, file: 'Samples/Tuba/tuba-sus-e2.wav'},
  	{note: 'E', octave: 3, file: 'Samples/Tuba/tuba-sus-e3.wav'},
  	{note: 'G', octave: 1, file: 'Samples/Tuba/tuba-sus-g1.wav'},
  	{note: 'G', octave: 2, file: 'Samples/Tuba/tuba-sus-g2.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Tuba/tuba-sus-g3.wav'}
  ],
  'Violas': [
  	{note: 'A', octave: 3, file: 'Samples/Violas/violas-sus-a3.wav'},
  	{note: 'A', octave: 4, file: 'Samples/Violas/violas-sus-a4.wav'},
  	{note: 'A', octave: 5, file: 'Samples/Violas/violas-sus-a5.wav'},
  	{note: 'C', octave: 3, file: 'Samples/Violas/violas-sus-c3.wav'},
  	{note: 'C', octave: 4, file: 'Samples/Violas/violas-sus-c4.wav'},
  	{note: 'C', octave: 5, file: 'Samples/Violas/violas-sus-c5.wav'},
  	{note: 'C', octave: 6, file: 'Samples/Violas/violas-sus-c6.wav'},
  	{note: 'D#', octave: 3, file: 'Samples/Violas/violas-sus-d%233.wav'},
  	{note: 'D#', octave: 4, file: 'Samples/Violas/violas-sus-d%234.wav'},
  	{note: 'D#', octave: 5, file: 'Samples/Violas/violas-sus-d%235.wav'},
  	{note: 'F#', octave: 3, file: 'Samples/Violas/violas-sus-f%233.wav'},
  	{note: 'F#', octave: 4, file: 'Samples/Violas/violas-sus-f%234.wav'},
  	{note: 'F#', octave: 5, file: 'Samples/Violas/violas-sus-f%235.wav'}
  ],
  'Violin': [
    {note: 'A#', octave: 3, file: 'Samples/Violin/violin-a%233.wav'},
  	{note: 'A#', octave: 4, file: 'Samples/Violin/violin-a%234.wav'},
  	{note: 'A#', octave: 5, file: 'Samples/Violin/violin-a%235.wav'},
  	{note: 'A#', octave: 6, file: 'Samples/Violin/violin-a%236.wav'},
  	{note: 'C#', octave: 4, file: 'Samples/Violin/violin-c%234.wav'},
  	{note: 'C#', octave: 5, file: 'Samples/Violin/violin-c%235.wav'},
  	{note: 'C#', octave: 6, file: 'Samples/Violin/violin-c%236.wav'},
  	{note: 'C#', octave: 7, file: 'Samples/Violin/violin-c%237.wav'},
  	{note: 'E', octave: 4, file: 'Samples/Violin/violin-e4.wav'},
  	{note: 'E', octave: 5, file: 'Samples/Violin/violin-e5.wav'},
  	{note: 'E', octave: 6, file: 'Samples/Violin/violin-e6.wav'},
  	{note: 'G', octave: 3, file: 'Samples/Violin/violin-g3.wav'},
  	{note: 'G', octave: 4, file: 'Samples/Violin/violin-g4.wav'},
  	{note: 'G', octave: 5, file: 'Samples/Violin/violin-g5.wav'},
  	{note: 'G', octave: 6, file: 'Samples/Violin/violin-g6.wav'}
  ]
}
